use geografii_db;

INSERT INTO answer_model (is_correct_answer, text) VALUES

(0, "Primul muzeu al satului din Romania"),
(0, "Pestera Comarnic"),
(0, "Morile de apa de la Rudaria"),
(1, "Prima cale ferata de munte din Romania"),
(0, "Baile Felix"),
(1, "Baile Herculane"),
(0, "Parcul National 'Domogled - Valea Cernei'"),
(0, "Cheile Nerei"),
(1, "Paralela de 45 grade trece pe langa cascada"),
(0, "Are o inaltime de peste 70 metri"),
(0, "Apa izvorului este bogata in magneziu"),
(0, "Se afla la baza celui mai inalt munte din Banat"),
(0, "Bucuresti"),
(1, "Timisoara"),
(0, "Arad"),
(0, "Brasov"),
(0, "O copie fidela a unui teatru spaniol"),
(0, "Construit doar din lemn"),
(1, "Cel mai vechi din Romania"),
(0, "Construit intr-o stanca"),
(0, "Varful Moldoveanu"),
(0, "Varful Vladeasa"),
(0, "Varful Pietrosul Rodnei"),
(1, "Varful Bihor"),
(0, "palarie"),
(1, "farfurie"),
(0, "pahar"),
(0, "creanga"),
(1, "Cea mai mare statiune cu functionare permanenta din tara"),
(0, "Se afla in judetul Salaj"),
(0, "Este statiune montana"),
(0, "Este cea mai veche statiune din Romania"),
(0, "Crisul Alb"),
(1, "Crisul Repede"),
(0, "Crisul Negru"),
(0, "Someș"),
(0, "Hațeg"),
(0, "Beclean"),
(1, "Șimleul Silvaniei"),
(0, "Chișineu-Criș"),
(0, "Una dintre cele mai vechi din tara"),
(0, "Intemeiata de Dragos Voda"),
(0, "Construita pe un lac"),
(1, "Cea mai inalta biserica de lemn din lume"),
(0, "Primul tren forestier cu aburi folosit in Romania"),
(1, "Ultimul tren forestier cu aburi din Europa"),
(0, "Cel mai vechi tren cu aburi din Romania"),
(0, "Cel mai folosit tren in ultimii 50 de ani in Romania"),
(1, "Pietrosul Rodnei"),
(0, "Hovarla"),
(0, "Obcina Mare"),
(0, "Obcina Mestecanis"),
(0, "Cel mai mare cimitir din Romania"),
(1, "Inspirat din cultura dacica, in care moartea era considerata un eveniment vesel"),
(0, "Cel mai vechi din Romania"),
(0, "Inspirat din cartile cu povesti ironice din limba slavona"),
(0, "Cascada Bigar"),
(0, "Cascada Duruitoarea"),
(1, "Cascada Cailor"),
(0, "Cascada Caraiman"),
(0, "Rezervatiile naturale"),
(0, "Cele mai vechi case de pe teritoriul Romaniei"),
(0, "Cele mai lungi trasee montane din tara"),
(1, "Bisericile si manastirile aflate in patrimoniu UNESCO"),
(0, "Alexandru cel Bun"),
(1, "Petru I Musat"),
(0, "Stefan cel Mare"),
(0, "Dumitrascu Cantacuzino"),
(1, "Cel mai mare crater vulcanic din Romania"),
(0, "Cea mai mare rezervatie naturala din Romania"),
(0, "Ruinele celei mai vechi cetati din Romania"),
(0, "Cele mai rare specii de flori"),
(0, "Botosani"),
(1, "Suceava"),
(0, "Cernauti"),
(0, "Radauti"),
(0, "Detine cel mai bogat muzeu"),
(0, "Este prima ctitorie religioasa a lui Stefan cel Mare"),
(1, "Locul constructiei a fost ales de Stefan cel Mare dupa ce a tras cu arcul"),
(0, "La picturile vechi ale manastirii s-a folosit foita de aur"),
(0, "Este ctitorita de Dragos I"),
(0, "Este singura biserica din lume amplasata subteran"),
(0, "Este construita pe varful unui munte"),
(1, "Este singura din Europa construita aproape integral din sare"),
(0, "Suceava"),
(1, "Iasi"),
(0, "Slanic"),
(0, "Roman"),
(1, "Universitatea Alexandru Ioan Cuza"),
(0, "Universitatea Babes-Bolyai"),
(0, "Universitatea din Bucuresti"),
(0, "Universitatea Transilvania"),
(0, "Arcul de Triumf"),
(1, "Obeliscul cu lei"),
(0, "Poarta Sarutului"),
(0, "Fantana Miorita"),
(0, "Vaslui"),
(0, "Galati"),
(1, "Iasi"),
(0, "Piatra Neamt"),
(0, "Tomis"),
(0, "Porolissum"),
(0, "Potaissa"),
(1, "Callatis"),
(0, "Parâng"),
(1, "Macin"),
(0, "Călimani"),
(0, "Zarand"),
(1, "Tropaeum Traiani"),
(0, "cetatea Tomis"),
(0, "Coloana Infinitului"),
(0, "plajă"),
(0, "Mihai Viteazul"),
(1, "Mircea cel Batran"),
(0, "Baiazid I"),
(0, "Vlad Țepeș"),
(0, "Constanta"),
(0, "Babadag"),
(1, "Tulcea"),
(0, "Mangalia"),
(0, "Mircea cel Batran"),
(0, "Stefan cel Mare"),
(0, "Mihai Viteazul"),
(1, "Carol I"),
(0, "Prahova"),
(1, "Buzau"),
(0, "Arges"),
(0, "Dambovita"),
(1, "Carol I"),
(0, "Ferdinand I"),
(0, "Carol II"),
(0, "Mihai"),
(0, "Turnu Magurele"),
(1, "Zimnicea"),
(0, "Corabia"),
(0, "Giurgiu"),
(0, "Vasile Alecsandri"),
(0, "Lucian Blaga"),
(1, "I.L. Caragiale"),
(0, "Regina Maria"),
(0, "Polovragi"),
(0, "Cotmeana"),
(0, "Tismana"),
(1, "Cozia"),
(0, "6"),
(1, "7"),
(0, "8"),
(0, "5"),
(1, "Ramnicu Valcea"),
(0, "Bucuresti"),
(0, "Iasi"),
(0, "Craiova"),
(0, "10"),
(1, "12"),
(0, "6"),
(0, "4"),
(0, "Horea,Closca,Crisan"),
(0, "Petru Maior"),
(1, "Tudor Vladimirescu"),
(0, "Nicolae Balcescu"),
(0, "Bucegi"),
(0, "Parâng"),
(0, "Godeanu"),
(1, "Făgăraș"),
(0, "Târgu-Mureș"),
(1, "Odorheiu Secuiesc"),
(0, "Sfântu Gheorghe"),
(0, "Cluj-Napoca"),
(1, "Bistrita-Nasaud"),
(0, "Cluj"),
(0, "Alba"),
(0, "Brașov"),
(0, "baroc"),
(1, "gotic"),
(0, "renascentist"),
(0, "romanic"),
(0, "Vasile Goldis"),
(0, "Aurel Lazar"),
(1, "Alexandru Vaida-Voievod"),
(0, "Carol II"),
(0, "Medievala"),
(0, "Primului Razboi Mondial"),
(0, "Interbelica"),
(1, "Comunista"),
(0, "5%"),
(1, "10%"),
(0, "25%"),
(0, "40%"),
(0, "Pastravul"),
(1, "Morunul"),
(0, "Bibanul"),
(0, "Stiuca"),
(1, "Sulina"),
(0, "Sfantu Gheorghe"),
(0, "Tulcea"),
(0, "Murighiol"),
(0, "Chilia"),
(0, "Sulina"),
(1, "Sfantu Gheorghe"),
(0, "Ostrov"),
(1, "Tomis"),
(0, "Histria"),
(0, "Medgidia"),
(0, "Callatis"),
(0, "Cea mai mare cetate din tara"),
(0, "Ultima cetate locuita"),
(1, "Cea mai veche asezare urbana din tara"),
(0, "Cea mai vizitata cetate din tara"),
(0, "Baroc"),
(0, "Gotic"),
(1, "Art Nouveau"),
(0, "Art Deco"),
(0, "100 km"),
(0, "185 km"),
(1, "245 km"),
(0, "355 km"),
(0, "Constanta"),
(0, "Mangalia"),
(0, "Tulcea"),
(1, "Sulina"),
(0, "Cea mai mare padure din Europa"),
(1, "Cea mai nordica padure subtropicala din Europa"),
(0, "Cea mai veche padure din Europa"),
(0, "Padurea aflata la cea mai inalta altitudine din tara"),
(0, "Mangalia"),
(0, "Sulina"),
(1, "Gura Portitei"),
(0, "Tuzla"),
(0, "Navodari"),
(1, "Vadu"),
(0, "Neptun"),
(0, "Mangalia"),
(0, "1052m"),
(0, "1511m"),
(1, "2212m"),
(0, "3405m"),
(0, "Sare"),
(1, "Namol"),
(0, "Pesti"),
(0, "Alge"),
(0, "Constanta"),
(1, "Mangalia"),
(0, "Tulcea"),
(0, "Sulina"),
(0, "1"),
(1, "2"),
(0, "3"),
(0, "4"),
(1, "Enisala"),
(0, "Histria"),
(0, "Carsium"),
(0, "Troesmis"),
(1, "Podului de cale ferata peste Dunare de la Cernavoda"),
(0, "Canalului Dunare – Marea-Neagra"),
(0, "Cazinoului din Constanta"),
(0, "Farului din Sulina"),
(0, "Eforie Nord"),
(0, "Costinesti"),
(1, "Mamaia"),
(0, "Venus"),
(0, "Patrat"),
(0, "Cerc"),
(1, "Stea"),
(0, "Hexagon"),
(0, "Sibiu"),
(1, "Brasov"),
(0, "Targu-Mures"),
(0, "Alba-Iulia"),
(1, "Viscri"),
(0, "Rimetea"),
(0, "Biertan"),
(0, "Rupea"),
(0, "Cluj"),
(0, "Sibiu"),
(0, "Harghita"),
(1, "Salaj"),
(0, "Un lac"),
(1, "Delta Transilvaniei"),
(0, "O campie"),
(0, "O padure"),
(1, "Somesul Mic"),
(0, "Somesul Mare"),
(0, "Somesul Cald"),
(0, "Somesul Rece"),
(0, "O casa"),
(1, "O biserica"),
(0, "Copaci"),
(0, "Un vapor"),
(0, "Aiud"),
(0, "Blaj"),
(0, "Dej"),
(1, "Turda"),
(0, "Muzeul National al Unirii din Alba-Iulia"),
(0, "Muzeul de Arta din Cluj-Napoca"),
(0, "Muzeul Civilizatiei Urbane din Brasov"),
(1, "Muzeul Brukenthal din Sibiu"),
(0, "Harghita si Mures"),
(0, "Bihor si Harghita"),
(0, "Covasna si Mures"),
(1, "Harghita si Covasna"),
(0, "Transalpina"),
(0, "Via Transilvanica"),
(1, "Transfagarasan"),
(0, "Valea Prahovei"),
(1, "Sfanta Ana"),
(0, "Lacul Rosu"),
(0, "Balea"),
(0, "Bucura"),
(0, "Rasnov"),
(1, "Sighisoara"),
(0, "Alba-Iulia"),
(0, "Fagaras"),
(1, "Biserica Neagra din Brasov"),
(0, "Catedrala Evanghelica din Sibiu"),
(0, "Catedrala Incoronarii din Alba-Iulia"),
(0, "Biserica Fortificată din Biertan"),
(0, "Bucuresti"),
(0, "Cluj-Napoca"),
(0, "Timisoara"),
(1, "Sibiu"),
(0, "Flora si fauna"),
(0, "Marime"),
(1, "Fenomene paranormale"),
(0, "Vechime"),
(0, "Peles"),
(1, "Bran"),
(0, "Corvinilor"),
(0, "Cantacuzino"),
(0, "Mica"),
(1, "Mare"),
(0, "Veche"),
(0, "Inalta"),
(0, "Palatul Parlamentului"),
(0, "Turnul Scarilor din Sibiu"),
(1, "Biserica Calvaria din Cluj-Napoca"),
(0, "Cazinoul din Constanta"),
(1, "Pestera Scarisoara"),
(0, "Lacul Rosu"),
(0, "Salina Turda"),
(0, "Perstera Ursilor"),
(0, "Teleorman"),
(0, "Ialomita"),
(1, "Harghita"),
(0, "Giurgiu"),
(0, "Olt"),
(0, "Arges"),
(1, "Dunarea"),
(0, "Siret"),
(1, "Sinaia"),
(0, "Busteni"),
(0, "Predeal"),
(0, "Azuga"),
(1, "Arges"),
(0, "Dambovita"),
(0, "Giurgiu"),
(0, "Prahova"),
(0, "Traian Vuia"),
(1, "Henri Coanda"),
(0, "Avram Iancu"),
(0, "Aurel Vlaicu"),
(0, "Ialomita"),
(0, "Dunarea"),
(0, "Siret"),
(1, "Dambovita"),
(0, "Targoviste"),
(1, "Bucuresti"),
(0, "Pitesti"),
(0, "Ploiesti"),
(0, "125m"),
(0, "98m"),
(0, "100m"),
(1, "137m"),
(0, "Copou"),
(0, "Cismigiu"),
(0, "Nicolae Romanescu"),
(1, "Herastrau"),
(0, "Ploiesti"),
(0, "Pitesti"),
(1, "Targoviste"),
(0, "Slobozia"),
(0, "Cantacuzino"),
(0, "Bran"),
(0, "Corvinilor"),
(1, "Peles"),
(1, "Primului Razboi Mondial"),
(0, "Celui de-al Doilea Razboi Mondial"),
(0, "Comunismului"),
(0, "Razboiului de Independenta a Romaniei"),
(0, "Pitesti"),
(0, "Bucuresti"),
(1, "Mioveni"),
(0, "Craiova"),
(0, "Vulcanic"),
(1, "De acumulare"),
(0, "Glaciar"),
(0, "Natural"),
(0, "178m"),
(0, "255m"),
(1, "300m"),
(0, "340m"),
(1, "Bucegi"),
(0, "Fagaras"),
(0, "Retezat"),
(0, "Apuseni"),
(1, "Burebista"),
(0, "Decebal"),
(0, "Deceneu"),
(0, "Scorilo"),
(1, "Arges"),
(0, "Ilfov"),
(0, "Braila"),
(0, "Vrancea"),
(0, "Pitesti"),
(0, "Targoviste"),
(1, "Ploiesti"),
(0, "Buzau"),
(0, "Bucuresti"),
(1, "Otopeni"),
(0, "Fetesti"),
(0, "Braila"),
(0, "Tisa"),
(0, "Mures"),
(1, "Somes"),
(0, "Bega"),
(0, "Bihor"),
(0, "Salaj"),
(1, "Timis"),
(0, "Cluj"),
(1, "Tisa"),
(0, "Mures"),
(0, "Somes"),
(0, "Bega"),
(0, "Raul Bega"),
(1, "Muntii Apuseni"),
(0, "Lacul Bezid"),
(0, "Raul Tisa"),
(0, "Tisa"),
(1, "Mures"),
(0, "Somes"),
(0, "Bega"),
(1, "Chrisola"),
(0, "Crisola"),
(0, "Chrisolas"),
(0, "Crisolas"),
(0, "Campia Covurlului"),
(0, "Campia Aradului"),
(0, "Campia Moldovei"),
(1, "Campia Crisurilor"),
(0, "Arad"),
(1, "Oradea"),
(0, "Zalau"),
(0, "Ineu"),
(0, "1"),
(0, "3"),
(1, "2"),
(0, "5"),
(0, "Alesd"),
(0, "Beius"),
(1, "Zalau"),
(0, "Ineu"),
(0, "Salaj"),
(1, "Bihor"),
(0, "Arad"),
(0, "Satu Mare"),
(1, "Marsul lui Iancu"),
(0, "Imnul Romaniei"),
(0, "Oda Bucuriei"),
(0, "Anotimpurile"),
(0, "Lac glaciar"),
(1, "Lac de acumulare"),
(0, "Lac carstic"),
(0, "Lac heliotermic"),
(1, "Cascada Vadu Crisului"),
(0, "Cascada Bulbuci"),
(0, "Cascada Oselu"),
(0, "Cascada Valul Miresei"),
(1, "Bihor"),
(0, "Salaj"),
(0, "Timis"),
(0, "Cluj"),
(0, "Lac glaciar"),
(1, "Lac de acumulare"),
(0, "Lac carstic"),
(0, "Lac heliotermic"),
(0, "Lipova"),
(0, "Nadlac"),
(1, "Arad"),
(0, "Sebis"),
(0, "Bihor"),
(1, "Arad"),
(0, "Salaj"),
(0, "Cluj"),
(0, "Lac glaciar"),
(0, "Lac de acumulare"),
(1, "Lac carstic"),
(0, "Lac heliotermic"),
(0, "vultur"),
(1, "scut"),
(0, "sabie"),
(0, "cavaler"),
(0, "Muntii Oasului"),
(0, "Muntii Tibles"),
(1, "Muntii Maramuresului"),
(0, "Muntii Rodnei"),
(1, "Cea mai intinsa depresiune a lantului Carpatic"),
(0, "un sat"),
(0, "o campie"),
(0, "un oras"),
(0, "dealul"),
(0, "campia"),
(1, "muntele"),
(0, "podis"),
(1, "Moldova"),
(0, "Transilvania"),
(0, "Bucovina"),
(0, "Crisana"),
(0, "somon roz"),
(1, "lostrita"),
(0, "somon Coho"),
(0, "somon rosu"),
(1, "Parcul Natural Muntii Maramuresului"),
(0, "Parcul National Retezat"),
(0, "Parcul National Piatra Craiului"),
(0, "Parcul National Cozia"),
(0, "Muntii Oasului"),
(0, "Muntii Tibles"),
(1, "Muntii Gutai"),
(0, "Muntii Rodnei"),
(0, "catolica"),
(1, "ortodoxa"),
(0, "islamica"),
(0, "reformata"),
(1, "barne"),
(0, "lemn"),
(0, "caramida"),
(0, "pamant"),
(0, "20"),
(1, "90"),
(0, "95"),
(0, "100"),
(1, "1300 m"),
(0, "1100 m"),
(0, "1000 m"),
(0, "1250 m"),
(1, "Varful Pietrosul"),
(0, "Varful Ignis"),
(0, "Varful Bran"),
(0, "Varful Omu"),
(0, "2 m"),
(0, "3 m"),
(0, "1,5 m"),
(1, "4 m"),
(1, "eliptica"),
(0, "de lentila"),
(0, "alungita"),
(0, "ascutita"),
(0, "Baia Mare"),
(0, "Borsa"),
(0, "Sighetu Marmatiei"),
(1, "Baia Sprie"),
(0, "Pasul Pintea"),
(0, "Pasul Gutin"),
(0, "Pasul Palatinu"),
(1, "Pasul Gutaiului"),
(1, "Varful Pietroasa"),
(0, "Varful Pietrosul"),
(0, "Varful Ignis"),
(0, "Varful Bran"),
(0, "Ardusat"),
(0, "Baia Mare"),
(1, "Sapanta"),
(0, "Baia Sprie"),
(0, "1890"),
(0, "1899"),
(0, "1920"),
(1, "1935"),
(0, "3 m"),
(1, "7 m"),
(0, "10 m"),
(0, "5 m"),
(0, "fagi"),
(0, "Taramul fagilor"),
(1, "Tara Fagilor"),
(0, "Padure de fagi"),
(1, "Cernauti"),
(0, "Suceava"),
(0, "Radauti"),
(0, "Vatra Dornei"),
(0, "1771"),
(0, "1769"),
(1, "1774"),
(0, "1782"),
(0, "Cernauti"),
(0, "Suceava"),
(0, "Radauti"),
(1, "Vatra Dornei"),
(1, "Manastirea Voronet"),
(0, "Manastirea Putna"),
(0, "Manastirea Moldovita"),
(0, "Manastirea Sucevita"),
(1, "Manastirea Voronet"),
(0, "Manastirea Putna"),
(0, "Manastirea Moldovita"),
(0, "Manastirea Sucevita"),
(0, "10 ani"),
(0, "8 luni"),
(0, "aproape 6 ani"),
(1, "aproape 4 luni"),
(1, "1488"),
(0, "1489"),
(0, "1455"),
(0, "1487"),
(0, "o casa"),
(0, "un parc"),
(1, "o biserica de lemn"),
(0, "un turn"),
(0, "Manastirea Voronet"),
(1, "Manastirea Putna"),
(0, "Manastirea Moldovita"),
(0, "Manastirea Sucevita"),
(0, "Manastirea Voronet"),
(1, "Manastirea Putna"),
(0, "Manastirea Moldovita"),
(0, "Manastirea Sucevita"),
(0, "5 ani"),
(1, "3 ani"),
(0, "7 ani"),
(0, "11 luni"),
(0, "Stefan cel Mare"),
(1, "Petru Rares"),
(0, "Despot Voda"),
(0, "Bogdan Lapusneanu"),
(1, "Stefan cel Mare"),
(0, "Petru Rares"),
(0, "Despot Voda"),
(0, "Bogdan Lapusneanu"),
(1, "gotic"),
(0, "bizantin"),
(0, "brancovenesc"),
(0, "Art nouveau"),
(0, "gotic"),
(1, "bizantin"),
(0, "art nouveau"),
(0, "brancovenesc"),
(0, "gotic"),
(1, "bizantin"),
(0, "brancovenesc"),
(0, "Art Nouveau"),
(1, "1583"),
(0, "1585"),
(0, "1573"),
(0, "1588"),
(0, "Stefan cel Mare"),
(1, "Petru Rares"),
(0, "Despot Voda"),
(0, "Bogdan Lapusneanu"),
(0, "Manastirea Putna"),
(0, "Manastirea Voronet"),
(1, "Manastirea Probota"),
(0, "Manastirea Sucevita"),
(0, "Carpatii Meridionali "),
(0, "Dunarea"),
(0, "Depresiunea Colinara a Transilvaniei"),
(1, "Carpatii Orientali"),
(1, "Agapia"),
(0, "Cozia"),
(0, "Prislop"),
(0, "Nicula"),
(0, "Ion Luca Caragiale"),
(0, "Mihai Eminescu"),
(1, "Vasile Alecsandri"),
(0, "Marin Sorescu"),
(1, "Humulesti"),
(0, "Ipotesti"),
(0, "Piatra-Neamt"),
(0, "Botosani"),
(0, "Siret"),
(0, "Prut"),
(0, "Nistru"),
(1, "Iza"),
(0, "Bacau"),
(1, "Galati"),
(0, "Botosani"),
(0, "Suceava"),
(1, "A fost primul roman laureat la Nobel"),
(0, "A descoperit penicilina"),
(0, "A fost primul roman care a zburat in spatiul cosmic"),
(0, "A fost primul explorator roman din Antarctica"),
(0, "Varza"),
(0, "Dovleac"),
(1, "Pepene verde"),
(0, "Cartof"),
(0, "Ciprian Porumbescu"),
(1, "George Enescu "),
(0, "Iosif Ivanovici"),
(0, "Gheorghe Zamfir"),
(0, "Iasi"),
(0, "Suceava"),
(1, "Botosani"),
(0, "Neamt"),
(1, "Alexandru Ioan Cuza "),
(0, "Constantin Brancoveanu"),
(0, "Avram Iancu"),
(0, "Carol I"),
(0, "Nipru"),
(0, "Siret"),
(1, "Prut "),
(0, "Nistru"),
(0, "Vrancea"),
(0, "Galati"),
(1, "Neamt "),
(0, "Botosani"),
(0, "Este un lac vulcanic"),
(1, "Este cel mai mare lac artificial din Romania "),
(0, "Este cel mai adanc lac din Romania"),
(0, "Se afla pe Transfagarasan"),
(1, "47  ani "),
(0, "60  ani "),
(0, "22 ani"),
(0, "36 ani"),
(1, "Bistrita "),
(0, "Bârlad"),
(0, "Buzău"),
(0, "Someș"),
(1, "Bacău "),
(0, "Focsani"),
(0, "Târgu-Neamț"),
(0, "Vaslui"),
(0, "Suceava"),
(0, "Neamț"),
(0, "Bacău"),
(1, "Galați "),
(1, "Dragoș I"),
(0, "Stefan cel Mare"),
(0, "Alexandru Ioan Cuza"),
(0, "Nicolae Mavrocordat"),
(1, "Dunăre "),
(0, "Prut"),
(0, "Marea Neagră"),
(0, "Olt"),
(1, "Drobeta Turnu-Severin "),
(0, "Resita"),
(0, "Slatina"),
(0, "Targoviste"),
(0, "Insula Simian"),
(0, "Insula Serpilor"),
(1, "Insula Ada Kaleh DA "),
(0, "Insula Ada"),
(0, " Craiova"),
(1, "Dragasani "),
(0, "Filiasi"),
(0, "Dabuleni"),
(1, "Craiova "),
(0, "Ramnicu Valcea"),
(0, "Targu Jiu"),
(0, "Brasov"),
(0, "Aici s-a nascut Constantin Brancusi"),
(1, "Scutul NATO anti-racheta"),
(0, "Casa Memoriala Ion Luca Caragiale"),
(0, "Este cel mai sudic punct din tara"),
(0, "Olt"),
(0, "Mures"),
(0, "Dunarea"),
(1, "Jiu "),
(0, "Calafat"),
(1, "Drobeta Turnu-Severin "),
(0, "Resita"),
(0, "Caracal"),
(0, "Carpatii Meridionali"),
(1, "Subcarpatii Getici "),
(0, "Depresiunea Colinara a Transilvaniei"),
(0, "Muntii Apuseni"),
(0, "MH "),
(1, "OT"),
(0, "GJ"),
(0, "DJ"),
(0, "1215 km"),
(0, "215 km"),
(1, "615 km "),
(0, "915 km"),
(0, "Praz"),
(0, "Cartofi"),
(1, "Pepeni "),
(0, "Visine"),
(0, "Baile Herculane"),
(0, "Baile Felix"),
(0, "Sovata"),
(1, "Baile Govora "),
(1, "Aici se afla singurul pod natural din lume deschis traficului rutier "),
(0, "Este cel mai populat judet din Oltenia"),
(0, "Este judetul in care s-a nascut Nicolae Ceausescu"),
(0, "De aici izvoraste Oltul"),
(0, "Manastirea Dintr-un Lemn"),
(0, "Manastirea Hurezi"),
(0, "Manastirea Polovragi"),
(1, "Manastirea Bârsana "),
(1, "Pestera Muierii, cea mai vizitata pestera din Romania "),
(0, "Vulcanii Noroiosi"),
(0, "Manastirea Cozia , ctitorita de Mircea cel Batran"),
(0, "Casa Memoriala 'Mihai Eminescu'"),
(0, "Transfagarasan"),
(0, "TransRarău"),
(1, "Transalpina "),
(0, "TransBucegi"),
(0, "Usturoi"),
(1, "Praz "),
(0, "Ceapa"),
(0, "Dovlecel"),
(0, "Herăstrău"),
(0, "B.Zăvoi"),
(0, "Constantin Brâncuși"),
(1, "Nicolae Romanescu "),
(0, "Salaj"),
(1, "Valcea "),
(0, "Bihor"),
(0, "Covasna"),
(0, "Targu-Jiu  "),
(0, "Rovinari"),
(0, "Tismana"),
(1, "Orsova "),
(0, "1"),
(0, "2"),
(1, "3 "),
(0, "4"),
(0, "Carpatii Orientali"),
(1, "Carpatii Occidentali "),
(0, "Muntii Apuseni"),
(0, "Carpatii Meridionali"),
(0, "Cascada Cailor"),
(0, "Cascada Vălul Miresei"),
(0, "Cascada Capra"),
(1, "Cascada Bigăr "),
(1, "Timisoara "),
(0, "Arad"),
(0, "Oradea"),
(0, "Resita"),
(0, "Timiș"),
(1, "Bega "),
(0, "Mureș"),
(0, "Caraș"),
(1, "Râul Tisa "),
(0, "Dunăre"),
(0, "Râul Timiș"),
(0, "Râul Mureș"),
(0, "Sannicolau Mare"),
(0, "Arad"),
(0, "Oradea"),
(1, "Beba Veche "),
(0, "Lipova"),
(0, "Debrecen"),
(0, "Sannicolau Mare"),
(1, "Pancevo "),
(0, "Traian"),
(1, "Decebal "),
(0, "Burebista"),
(0, "Mircea cel Batran"),
(0, "Timisoara"),
(0, "Mehedinti"),
(1, "Caras-Severin "),
(0, "Drobeta Turnu-Severin"),
(0, "Aici se afla cel mai vechi teatru din Romania"),
(1, "Aici se afla Muzeul de Locomotive cu Abur, unic in tara noastra "),
(0, "Se afla in judetul Mehedinti"),
(0, "Este cel mai populat oras din Banat"),
(1, "1919 "),
(0, "1918"),
(0, "1859"),
(0, "1945"),
(0, "Resita "),
(0, "Drobeta Turnu-Severin"),
(1, "Baziaș "),
(0, "Vidin"),
(0, "Dunăre-Marea Neagră"),
(1, "Râul Bega"),
(0, "Râul Mureș"),
(0, "Râul Olt"),
(0, "Timișoara"),
(0, "Băile Felix"),
(1, "Băile Herculane"),
(0, "Reșița"),
(0, "Timis "),
(0, "Iasi"),
(0, "Mehedinti"),
(0, "Hunedoara"),
(0, "Este primul oras european care a introdus iluminatul electric stradal"),
(0, "Este primul oras din Europa de Est in care s-a circulat cu tramvaiul"),
(0, "Are peste  300.000 locuitori"),
(1, "Are aproximativ 200.000 locuitori "),
(0, "Muntii Apuseni"),
(1, "Muntii Poiana-Rusca "),
(0, "Muntii Rodnei"),
(0, "Muntii Bucegi"),
(0, "Oradea"),
(0, "Cluj-Napoca"),
(1, "Timisoara "),
(0, "Arad"),
(1, "Traian Vuia "),
(0, "Ana Aslan"),
(0, "Petrache Poenaru"),
(0, "Emil Racovita");

SELECT * FROM answer_model;