use geografii_db;

INSERT INTO question_model (hint, points, text) VALUES

("Este administrata de infrastructura nationala feroviara", 10, "Ce se afla pe linia Oravita-Anina?"),
("Numele statiunii vine de la fiul Zeus si al Alcmenei", 10, "Care este cea mai veche statiune turistica din tara?"),
("Este numele unei edituri, dar si a multor companii de turism", 10, "Ce lucru este adevarat depre Cascada Bigar?"),
("Este municipiul de resedinta al judetului Timis", 10, "Din ce oras a pornit revolutia care a pus capat comunismului?"),
("Nu te-ai fi asteptat sa fie atat de batran", 10, "Teatrul din Oravita este:"),
("Seamana cu numele unui judet din zona lui.", 10, "Care este cel mai inalt varf din muntii Apuseni ? "),
("Il gasesti in bucatarie", 10, "Regionalismul 'blid' inseamna"),
("Oamenii vin tot timpul pentru apa termala.", 10, "Ce este adevarat despre Baile Felix ?"),
("Nu curge chiar atat de ...", 10, "Ce râu trece prin Oradea?"),
("Existau bomboane cu denumirea asemanatoare", 10, "Care dintre urmatoarele orase se afla in judetul Salaj?"),
("Se vede de la o distanta de 5 km", 10, "Manastirea din Peri-Sapanta este:"),
("Nu mai are niciun mostenitor", 10, "Mocanita este cunoscuta fiind:"),
("Este cel mai inalt pisc muntos din Muntii Rodnei cu 2303 metri", 10, "Cel mai inalt varf din Maramures este:"),
("Nu era considerat un eveniment trist", 10, "Cimitirul Vesel este:"),
("Legenda spune despre ea ca este cascada unde caii si-au pierdut aripile", 10, "Care este cea mai inalta cascada din Romania?"),
("Sunt atat de multe incat credinciosii care merg cu autobuzul se plang regulat de febra musculara pe care o au de la facut cruce", 10, "Ce se afla in numar mare in regiunea bucovineana?"),
("Tot el a mutat capitala Moldovei de la Siret la Suceava, fiind numit 'fiul Musatei'", 10, "Cine a construit cetatea de Scaun a Sucevei?"),
("In prezent nu reprezinta nicio amenintare, acesta fiind stins", 10, "Ce se afla in Parcul National Calimani?"),
("Numele provine din maghiarul 'szucs', care inseamna cojocar", 10, "Care este cel mai mare oras din Bucovina?"),
("In locul in care se afla sageata s-a construit altarul manastirii", 10, "Manastirea Putna este cunoscuta pentru ca:"),
("A fost construita cu ajutorul minerilor pentru ajutor si ferirea de accidente", 10, "Pentru ce esta cunoscuta Biserica 'Sf. Varvara' din Targu Ocna?"),
("A fost atat capitala Moldovei, cat si a Regatului Romaniei atunci cand Bucurestiul s-a aflat sub ocupatie germana ", 10, "Unde se afla cea mai veche gradina botanica?"),
("A fost primul domnitor al Principatelor Unite si al statului national Romania", 10, "Care a fost prima universitate infiintata din Romania?"),
("Simbolul are legatura cu moneda nationala a tarii", 10, "Care a fost primul monument romanesc?"),
("Este orasul primei mari uniri, iar pe dealul Copoului se afla ce mai veche universitate din Romania, Univ. 'Al I. Cuza'", 10, "Care este cel mai mare oras din Moldova?"),
("Doar 2 cetatii se afla in judetul Constanta ", 10, "In jurul cărei cetăți a fost construit orasul Mangalia?"),
("Exista si un oras cu acest nume", 10, "In Dobrogea se afla cei mai vechi munti din tara. Cum se numesc?"),
("Comemoreaza victoria romanilor asupra dacilor", 10, "Pentru ce este cunoscut  satul Adamclisi?"),
("S-a nascut in 1355", 10, "Ce conducator a alipit Dobrogea la Țara Româneasca ?"),
("Este resedinta de judet", 10, "Care este al doilea cel mai populat oras din Dobrogea?"),
("Sotia lui era Elisabeta", 10, "Cine este inmormantat la Curtea de Arges?"),
("Judetul Vrancea se afla in apropiere", 10, "In ce judet se afla Vulcanii Noroiosi?"),
("Acest rege a intrat pentru prima oara in tara cu alta identitate", 10, "La initiativa carui rege a fost construit castelul Peles?"),
("Se afla in judetul Teleorman", 10, "Care este cea mai sudica localitate din Romania ?"),
("Satul in care s-a nascut ii poarta acum numele", 10, "Ce nume poarta Teatrul National din Bucuresti?"),
("Se afla pe malul Oltului", 10, "La ce manastire este inmormantat Mircea cel Batran?"),
("Valaorea cautata se afla in intervalul [7,10]", 10, "Prin cate judete trece Oltul ?"),
("De aici provine echipa de handbal feminin Oltchim ", 10, "In ce oras s-au auzit pt prima oara acordurile imnului national  actual"),
("Cate stele sunt pe steagul Uniunii Europene?", 10, "Cate scaune sunt la Masa Tacerii ?"),
("Are acelasi prenume precum autorul volumului 'Flori de mucigai?'", 10, "Cine a condus Revolutia din 1821?"),
("Transfagarasanul se afla in apropriere. ", 10, "In ce masiv este situat Vf. Moldoveanu ?"),
("Se afla in judetul Harghita", 10, "Prin ce oras trece Târnava Mare?"),
("In acest judet se afla si lacul Colibita", 10, "In ce judet s-a nascut Liviu Rebreanu ?"),
("Are acelasi stil arhitectural ca Domul din Milano", 10, "In ce stil arhitectural este construit Castelul Corvinilor?"),
("S-a nascut in Austro-Ungaria", 10, "Cine a citit declaratia de independenta a Transilvaniei la Budapesta?"),
("Ceausescu era presedinte.", 10, "Canalul Dunare – Marea-Neagra a fost construit in perioada:"),
("Valoarea se afla in intervalul [0-20].", 10, "Cat la suta din suprafata Deltei este reprezentata de uscat?"),
("Poate atinge o lungime de 5-7 m.", 10, "Cel mai mare peste de apa dulce din lume se gaseste in Delta si este:"),
("Cel mai estic oras din Romania.", 10, "Care este singurul oras din Delta care are port si la Dunare si la Marea Neagra?"),
("Acelasi nume cu resedinta judetului Covasna.", 10, "Care este cel mai vechi brat al Dunarii?"),
("Asa se numea orasul Constanta in trecut.", 10, "Cum se numeste Portul Turistic din Constanta?"),
("Intemeiata in jurul anului 657 i.Hr.", 10, "Cetatea Histria este cunoscuta ca fiind:"),
("A pornit din Belgia si Franta.", 10, "In ce stil architectural este construit Cazinoul din Constanta?"),
("Valoare cuprinsa in intervalul [150-250].", 10, "Care este lungimea litoralului romanesc?"),
("Se poate ajunge acolo doar cu barca.", 10, "Care este orasul situat la cea mai joasa altitudine din Romania (4m)?"),
("Are o caracteristica unica in aceasta parte a Europei.", 10, "Padurea Letea este:"),
("Se afla in judetul Tulcea.", 10, "Cum se numeste localitatea situata pe o fasie ingusta de nisip intre Delta si Marea Neagra?"),
("Se afla la nord de Constanta.", 10, "Una dintre cele mai cunoscute plaje salbatice de pe litoralul romanesc este in:"),
("Valoarea este cuprinsa in intervalul [1500-2500].", 10, "Care este adancimea maxima a Marii Negre?"),
("Are proprietati terapeutice.", 10, "Lacul Techirghiol a devenit celebru pentru:"),
("Oras apropiat de granite cu Bulgaria.", 10, "Cel mai vechi lacas de cult musulman din Romania este Moscheea Esmahan-Sultan si se afla in orasul:"),
("Judetele respective au iesire la mare.", 10, "Din cate judete este alcatuita Dobrogea?"),
("Se afla in judetul Tulcea.", 10, "Care este singura cetate medievala din Dobrogea?"),
("Singura centrala nuclear din tara se afla in apropiere.", 10, "Inginerul Anghel Saligny este cunoscut pentru proiectarea:"),
("Se afla in nordul orasului Constanta.", 10, "Cea mai mare si populara statiune de pe litoralul romanesc este:"),
("Are 5 colturi.", 10, "Cetatea Alba Carolina din Alba-Iulia este construita in forma de:"),
("Acesta are un aeroport in constructie.", 10, "Biserica Neagra, cel mai mare lacas de cult in stil gotic din Sud-Estul Europei, se afla in orasul:"),
("Se afla in judetul Brasov.", 10, "Satul care a devenit celebru datorita printului Charles este: "),
("Resedinta judetului este Zalau.", 10, "Rezervatia naturala “Gradina Zmeilor” poate fi vizitata in judetul:"),
("Rezervatie unica in Romania.", 10, "Stufarisul de la Sic este cunoscut ca fiind:"),
("Trece si prin Dej.", 10, "Ce rau trece prin Cluj-Napoca?"),
("Are o cruce.", 10, "Ce se poate vedea in lacul Belis, atunci cand nivelul apei scade?"),
("Are o salina renumita.", 10, "Mormantul lui Mihai Viteazul se poate gasi in apropierea orasului:"),
("Oras renumit pentru Targul de Craciun.", 10, "Primul muzeu deschis publicului pe teritoriul României de astăzi şi cel mai mare muzeu din sud-estul Europei este:"),
("Se afla in Tinutul Secuiesc.", 10, "Care sunt judetele cu populatie majoritar maghiara?"),
("Balea Lac se gaseste acolo.", 10, "Drumul care traverseaza Muntii Fagaras, considerat unul dintre cele mai spectaculoase drumuri din lume este:"),
("Se afla in judetul Harghita.", 10, "Care este singurul lac vulcanic din Romania?"),
("Se afla in judetul Mures.", 10, "Unde se afla singura cetate medievala locuita din Europa?"),
("Este cel mai mare lacas de cult in stil gotic din Sud-Estul Europei.", 10, "Unde se gaseste cea mai mare orga din lume si cel mai mare clopot din Romania?"),
("A fost capitala culturala europeana in 2007.", 10, "Muzeul Astra este al doilea cel mai mare muzeu in aer liber din lume si se afla in orasul:"),
("OZN.", 10, "Padurea Hoia Baciu este cunoscuta in intreaga lume pentru:"),
("Este cunoscut ca fiind Castelul lui Dracula.", 10, "Cel mai vizitat castel din Romania este:"),
("Celalalte depresiuni sunt mai mici.", 10, "Depresiunea Transilvaniei este cea mai ….. depresiune colinara din Europa:"),
("Se afla in inima Transilvaniei.", 10, "Care este cea mai veche cladire din Romania (>1000 ani)?"),
("Se afla in judetul Alba.", 10, "Cel mai mare ghetar subteran din Romania se gaseste in:"),
("Resedinta judetului este Miercurea Ciuc.", 10, "Care judet nu face parte din Muntenia?"),
("Izvoraste din Germania.", 10, "Care este principala apa curgatoare care strabate aceasta regiune?"),
("In aceasta localitate se poate vizita Casa memoriala “George Enescu”.", 10, "In ce localitate se gaseste Castelul Peles?"),
("Resedinta judetului este Pitesti.", 10, "Cetatea Poenari poate fi vizitata in judetul:"),
("Aeroportul International din Otopeni ii poarta numele.", 10, "Motorul modern cu reacție a fost inventat de bucureșteanul:"),
("Izvoraste din Muntii Fagaras.", 10, "Ce rau trece prin Bucuresti?"),
("Este cel mai mare oras din tara.", 10, "Care a fost primul oras din lume iluminat cu petrol?"),
("A doua cea mai inalta cladire din tara are 120m.", 10, "Ce inaltime are cea mai inalta cladire din Romania, Sky Tower – Bucuresti?:"),
("Se afla in Bucuresti.", 10, "Care este cel mai mare parc din Romania, avand o suprafata de 110 hectare?"),
("A fost cetatea de scaun a Tarii Romanesti.", 10, "Care este resedinta judetului Dambovita?"),
("Se afla in judetul Prahova.", 10, "Care a fost primul castel din Europa iluminat electric in totalitate?"),
("Razboiul a avut loc intre anii 1914-1918.", 10, "Crucea de pe Caraiman este un monument dedicat eroilor:"),
("Se afla in judetul Arges", 10, "Unde se afla cea mai mare uzina auto din Romania? "),
("Lacul fost creat prin constructia barajului Vidraru.", 10, "Lacul Vidraru este un lac:"),
("Valoarea se afla in intervalul [250-320].", 10, "Care este altitudinea maxima a Campiei Romane?"),
("Vf. Omu este cel mai inalt varf din acesti munti.", 10, "In ce munti se gasesc Babele si Sfinxul?"),
("A fost regele geto-dacilor din 88 î.Hr. pana in 44 î.Hr. si intemeitorul statului dac", 10, "Din ce mare regat dac a facut parte teritoriul munteniei?"),
("Resedinta judetului este orasul Pitesti", 10, "Care este cel mai mare judet din Muntenia?"),
("OMV are o rafinarie langa orasul respectiv", 10, "Care este orasul cu cele mai multe rafinarii din Romania?"),
("Se afla in judetul Ilfov", 10, "Unde se afla cel mai important aeroport din Romania?"),
("Poate fi … Mare, … Mic, … Rece sau … Cald.", 10, "Ce rau se afla in nordul regiunii?"),
("Judetul care are ca resedinta orasul Timisoara.", 10, "Cu ce judet se invecineaza Arad la sud?"),
("Rimeaza cu Pisa.", 10, "Ce rau delimiteaza regiunea la vest?"),
("Acolo se afla si Cheile Turzii.", 10, "Care este limita naturala din estul regiunii?"),
("Exista un judet cu acelasi nume.", 10, "Ce rau delimiteaza regiunea la sud?"),
("Suna grecesc.", 10, "Care este denumirea antica a Crisurilor?"),
("Exista rau cu acelasi nume.", 10, "Care campie face parte din Campia Tisei?"),
("Este resedinta judetului Bihor.", 10, "Ce oras reprezinta capitala traditionala a Crisanei?"),
("Tariile respective sunt vecine", 10, "Pe cate teritorii se intinde Crisana?"),
("Se afla langa Cetatea Porolissum.", 10, "Care este municipiul de resedinta al judetului Salaj?"),
("Judetul in care se afla orasul Oradea.", 10, "In ce judet se afla Pestera Ursilor?"),
("Este compus de George Baritiu.", 10, "Ce canta la ore fixe orologiul din Turnul Primariei Oradea?"),
("Lac artificial format prin retinerea apei unui curs de apa.", 10, "Ce tip de lac este Lacul Lesu?"),
("Exista o comuna cu acelasi nume.", 10, "Ce cascada se afla in Muntii Padurea Craiului?"),
("Judetul in care se afla orasul Oradea.", 10, "Cu ce judet se invecineaza Arad la nord?"),
("Lac artificial format prin retinerea apei unui curs de apa.", 10, "Ce tip de lac este Lacul Taut?"),
("Are acelasi nume.", 10, "Care este resedinta judetului Arad?"),
("Are resedinta de judet la Arad.", 10, "In ce judet se afla casa memoriala Ioan Slavici?"),
("Carst", 10, "Ce tip de lac este Lacul Petea?"),
("Este folosit in lupte pentru aparare.", 10, "Sub ce forma e stema Crisanei?"),
("Poarta denumirea regiunii.", 10, "Ce munti delimiteaza Maramuresul la nord si la est?"),
("E o forma de relief.", 10, "Ce reprezinta Tara Maramuresului?"),
("E la inaltime.", 10, "Forma de relief predominanta este…"),
("‘Parjoale’ e un regionalism din acea zona si inseamna chiftele.", 10, "Spre ce regiune face trecerea Pasul Prislop?"),
("Poarta numele unei carti scrise de Vasile Voiculescu.", 10, "Ce specie rara de somon traieste in raurile din Maramures?"),
("Poarta numele regiunii.", 10, "Care este cea mai mare arie protejata din Romania dupa Delta Dunarii?"),
("Exista un fruct cu un nume asemanator.", 10, "In ce munti se afla Creasta Cocosului?"),
("Religie predominanta in Romania.", 10, "Ce tip de manastire este Manastirea Barsana?"),
("Exista un aparat de gimnastica cu acelasi nume.", 10, "Din ce este construita Manastirea Barsana?"),
("Valoarea se afla in intervalul [75,95].", 10, "Cati metri are caderea de apa a Cascadei Cailor?"),
("Se afla in intervalul [1150,1350].", 10, "La ce altitudine se afla Cascada Cailor?"),
("Piatra.", 10, "Cel mai inalt varf din Carpatii Orientali este:"),
("E mai adanc decat credeai.", 10, "Ce adancime are Lacul Albastru?"),
("Forma de elipsa", 10, "Ce forma are Lacul Albastru"),
("A fost unul dintre centrele miniere importante din Maramures.", 10, "In ce oras se afla Lacul Albastru?"),
("Seamana cu numele original.", 10, "Care dintre urmatoarele denumiri nu se refera la Pasul Gutai?"),
("Piatra.", 10, "Pe ce varf se poate gasi Sfinxul Oasului?"),
("Exista un rau cu acelasi nume.", 10, "In ce localitate se afla Cimitirul Vesel?"),
("Dupa anul 1900.", 10, "In ce an a fost fondat Cimitirul Vesel?"),
("Valoare se afla in intervalul [4,9]", 10, "Cati metri are caderea de apa a Cascadei Sipot?"),
("Tara unui arbore.", 10, "Ce reprezinta cuvantul Bucovina in limba germana?"),
("Se afla in Ucraina", 10, "Care este resedinta Bucovinei?"),
("Dupa 1770.", 10, "In ce an a fost atestata Bucovina?"),
("Exista un producator de apa cu un nume similar.", 10, "Care oras este denumit si “Perla Bucovinei”? "),
("Se afla langa Gura Humorului.", 10, "Care manastire a fost supranumita “Capela Sixtina a Estului”?"),
("Se afla in zona orasului Gura Humorului.", 10, "Care constructie reprezinta una dintre cele mai importante ctitorii ale lui Stefan cel Mare?"),
("Un timp record pentru acele vremuri si pentru o astfel de constructie.", 10, "In cat timp a fost ridicata Manastirea Voronet?"),
("Intre 1480 si 1490.", 10, "In ce an a fost ridicata Manastirea Voronet?"),
("Lacas de cult.", 10, "Ce se afla pe locul in care a fost construita Manastirea Voronet?"),
("Este unul dintre cele mai importante centre culturale, religioase si artistice romanesti.", 10, "Care manastire a fost supranumita “Ierusalimul Neamului Romanesc”?"),
("Este unul dintre cele mai importante centre culturale, religioase si artistice romanesti.", 10, "In ce manastire se afla mormantul lui Stefan cel Mare?"),
("Se afla in intervalul 2-6 ani.", 10, "Cati ani a durat construirea Manastirii Putna?"),
("Fiul lui Stefan cel Mare.", 10, "Cine este ctitorul Manastirii Moldovita?"),
("Fiul lui Bogdan al II-lea si al Mariei Oltea.", 10, "Cine este ctitorul Manastirii Putna?"),
("Mai este numit si stilul arcului ascutit.", 10, "Ce stil arhitectonic are Manastirea Putna?"),
("A existat un imperiu cu acelasi nume.", 10, "Ce stil arhitectonic are Manastirea Moldovita?"),
("A existat un imperiu cu acelasi nume.", 10, "Ce stil arhitectonic are Manastirea Sucevita?"),
("Intre 1575 si 1585.", 10, "In ce an a fost inceputa construirea Manastirii Sucevita?"),
("Fiul lui Stefan cel Mare.", 10, "Cine este ctitorul Manastirii Putna?"),
("Manastirea este mentionata in romanul “Nicoara Potcoava” al lui Mihail Sadoveanu.", 10, "Unde se afla mormantul lui Petru Rares?"),
("In forma de relief respectiva, atitudinea maxima depaseste 2000 metri", 10, "Din punct de vedere geografic, Moldova este delimitata la Vest de:"),
("Se afla in comuna cu acelasi nume, din judetul Neamt", 10, "Care dintre urmatoarele manastiri se afla in regiunea Moldova?"),
("este poate cel mai celebru creator de pasteluri din literatura romana", 10, "Cum se numeste primul teatru national din Romania, aflat la Iasi?"),
("'Amintiri din copilarie' incepe chiar cu prezentarea istoriei acestui sat", 10, "In ce localitate s-a nascut  Ion Creanga, unul dintre cei mai importanti scriitori romani si autor al 'Amintirilor din copilarie'?"),
("Raul respectiv se afla in Maramures si este afluent al Tisei", 10, "Care dintre urmatoarele rauri nu se afla in regiunea Moldova ( care cuprinde si Republica Moldova )?"),
("Este situat pe Dunare", 10, "Dupa Iasi, care este cel mai populat oras din Moldova?"),
("S-a remarcat in domeniul biologiei celulare", 10, "Care dintre urmatoarele variante sunt adevarate despre George Emil Palade, nascut la Iasi?"),
("Se consuma in lunile de vara", 10, "Regionalismul 'harbuz' din graiul moldovenesc inseamna?"),
("In ultima parte a vietii sale, acesta s-a exilat la Paris", 10, "Compozitor al  'Rapsodiilor romane', nascut in judetul Botosani si considerat cel mai mare muzician roman."),
("Judetul se afla la granita cu Republica Moldova", 10, "In ce judet se afla casa memoriala a poetului Mihai Eminescu?"),
("A abdicat in 1866", 10, "Originar din Bârlad, judetul Vaslui, cine a fost primul domnitor al Principatelor Unite?"),
("2 dintre aceste 4 rauri/fluvii nici nu patrund pe teritoriul Romaniei", 10, "Frontiera fluviala dintre Romania si Republica Moldova este reprezentata de:"),
("Acest judet este cunoscut si pentru frumusetea Masivului Ceahlau din C. Orientali", 10, "In ce judet se afla orasul Roman?"),
("Lacul s-a format intre anii 1950 si 1960 dupa construirea unui baraj", 10, "Ce este adevarat despre Lacul Bicaz?"),
("S-a nascut in 1433 si a murit in 1504", 10, "Nascut in  Borzesti, judetul Bacau, Stefan cel Mare a avut cea mai lunga domnie din Tarile Romane si anume..."),
("Raul respectiv strabate Carpatii Orientali si se varsa in Siret", 10, "Ce rau trece prin orasul Bacau?"),
("Bacovia este unul dintre pseudonimele sale, acest nume fiind totusi relevant in ceea ce priveste judetul din care provine", 10, "Cel mai important poet simbolist roman, George Bacovia s-a nascut in orasul..."),
("Este vecin cu judetul Braila", 10, "Care dintre urmatoarele judete este cel mai sudic?"),
("Descalecatorul ... a trait in secolul 14", 10, "Conform legendei Descălecatului Moldovei, cine este considerat primul voievod al Țării Moldovei?"),
("Are locul de varsare aproape de orasul Galati", 10, "Unde se varsa râul Siret?"),
("Localitatea s-a dezvoltat  pornind de la  un castru roman important", 10, "Care este resedinta judetului Mehedinti?"),
("Actiunea unui film din anul 2001 in care joaca Stefan Banica Jr si Jean Constantin Popescu se desfasoara pe aceasta insula", 10, "Cum se numea insula de pe Dunare , acoperita in 1970 de apele lacului hidrocentralei Portile de Fier I?"),
("Valcea este un judet mai 'dragut'", 10, "Care dintre urmatoarele orase nu se afla in judetul Dolj?"),
("Unii oameni se refera la acest oras si zona din jurul lui ca 'bănie'", 10, "Care este cel mai populat oras din Oltenia?"),
("Satul are importanta mondiala , nu doar nationala", 10, "Pentru ce este cunoscut satul Deveselu din judetul Olt?"),
("Are cea mai mica lungime dintre toate variantele", 10, "Ce rau trece prin municipiul Targu-Jiu?"),
("Raspunsul corect este o resedinta de judet", 10, "Unde se afla podul lui Traian, construit de Apolodor din Damasc? "),
("Denumirea variantei corecte de raspuns este sugestiva..", 10, "Podisul Getic este marginit la Nord de ..."),
("Slatina este municipiul de resedinta pentru acest judet", 10, "Ce indicativ auto au masinile din orasul Slatina?"),
("Raul are o lungime cuprinsa intre 500 si 1000 de km.", 10, "Ce lungime are raul Olt?"),
("Face parte din familia Cucurbitaceae", 10, "Localitatea Dabuleni este cunoscuta pentru cultura de:"),
("In localitatea respectiva, exista o manastire cu acelasi nume", 10, "Care dintre urmatoarele statiuni balneare se afla in judetul Valcea?"),
("Exista o multime de legende populare legate de raspunsul corect", 10, "Ce este adevarat despre judetul Mehedinti?"),
("Manastirea respectiva se afla in judetul Maramures", 10, "Care dintre urmatoarele manastiri nu se afla in Oltenia?"),
("In timpuri stravechi , aici se adaposteau femei si copii atunci cand barbatii plecau la razboi", 10, "Ce se afla in comuna Baia de Fier din judetul Gorj?"),
("NU este soseaua care trece pe langa lacul Bâlea, din Fagaras", 10, "Care este cea mai inalta sosea din Romania, facand legatura intre Oltenia si Transilvania?"),
("Se aseamana puternic cu ceapa", 10, "In filmul ”Nea Mărin miliardar” , in servieta personajului principal se afla o legumă reprezantivă Olteniei și anume:"),
("A fost proiectat  la initiativa primarului Craiovei din anul 1900, parcul purtandu-i ulterior numele", 10, "Cum se numeste parcul din Craiova considerat cea mai mare zona verde urbana din Romania?"),
("Aici s-au auzit pentru prima data acordurile imnului actual national al Romaniei", 10, "Care este primul județ atestat din Romania?"),
("In orasul respectiv exista un port la Dunare", 10, "Care dintre urmatoarele orase nu se afla in judetul Gorj?"),
("Toate tarile sunt vecine intre ele", 10, "Pe teritoriul cator tari se intinde provincia istorica Banat?"),
("Muntii Apuseni sunt si ei la randul lor subdiviziune a aceluiasi lant muntos ca si Muntii Banatului.", 10, "Muntii Banatului sunt o subdiviziune a carui lant muntos?"),
("Cascada respectiva s-a prabusit chiar in anul 2021", 10, "Care dintre urmatoarele cascade se afla in Parcul National Cheile Nerei-Beușnița?"),
("Acest oras a fost ales sa fie Capitala Europeana a Culturii in anul 2023", 10, "Care a fost primul oras iluminat electric din Europa?"),
("Timisoara este supranumita 'orasul de pe ...'", 10, "Ce râu trece prin orasul Timisoara?"),
("Râul/fluviul respectiv curge în principal pe teritoriul Ungariei", 10, "Unde se varsa Raul Bega?"),
("Este o comuna situata in judetul Timisoara", 10, "Cel mai vestic punct din tara este:"),
("Are o populatie de 120.000 si este la periferia orasului Belgrad", 10, "Care dintre urmatoarele localitati se afla in Banatul Sarbesc?"),
("A fost regele Daciei intre anii 87 si 106", 10, "Chipul carei personalitati istorice este sculptat intr-o stanca , pe malul stang al Dunarii , langa Orsova?"),
("Un alt municipiu din judetul respectiv este Caransebeș", 10, "Resita este resedinta judetului ..."),
("Banatul a oferit Romaniei cateva premiere in domeniul transporturilor, una dintre ele fiind primul tramvai de la Timisoara sau ...", 10, "Ce este adevarat despre orasul Resita?"),
("S-a petrecut in secolul 20, pe data de 3 august", 10, "In ce an s-a alipit Banatul de Romania?"),
("Localitatea respectiva nu este resedinta de judet", 10, "Prin ce localitate intra Dunarea pe teritoriul Romaniei?"),
("Se afla in judetul Timis", 10, "Care a fost primul canal navigabil din România?"),
("Se afla in cea mai veche statiuni balneare cu bai termale din Romania", 10, "Baile Imperiale Austriece ( Baile ”Neptun”), monument istoric național se află în ..."),
("Aici a avut loc in 1848 a doua Adunare nationala a romanilor din Banat", 10, "In ce judet se afla orasul Lugoj , cu o populatie de aproximativ 45.000?"),
("La recensamentul din 2011, a fost al 3-lea cel mai populat oras din Romania", 10, "Ce nu este adevarat despre Timisoara, cel mai mare oras din provincia Banat?"),
("Acesti munti au inaltimi relativ reduse , altitudinea maxima fiind 1382", 10, "Care dintre urmatorii munti se afla pe teritoriul Banatulu?"),
("Pe 15 decembrie 1989 au fost primele proteste in ”orasul rozelor”", 10, "Din ce oras al tarii a pornit Revolutia din 1989?"),
("A inventat primul avion cu mijloace proprii de propulsie", 10, "Ce personalitate istorica , pionier al aviatiei mondiale, s-a nascut la Timisoara?");


SELECT * FROM question_model;
